### ISSUE TITLE
Shellcheck warnings

### ISSUE THREAD

**Issue by oxr463** [rofl0r/install.sh#2]
```
Line 28:
shift $(($OPTIND - 1))
         ^-- SC2004: $/${} is unnecessary on arithmetic variables.
 
Line 31:
src=$1
^-- SC2034: src appears unused. Verify use (or export if used externally).
```

**Comment by rofl0r** [comment]
yes, src is indeed unused, but having it there serves as documentation what the later use of `$1` is about. the other warning is merely a style choice. i prefer not to do any changes, as the version used here is battle-tested and used without issues in many projects. is there a good reason why you'd like to see these warnings fixed?

**Comment by oxr463** [comment]
No, no good reason in particular.
